/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        // Primitives
        violet: 'var(--violet)',
        'deep-violet': 'var(--deep-violet)',
        'soft-violet': 'var(--soft-violet)',
        cyan: 'var(--cyan)',
        'deep-cyan': 'var(--deep-cyan)',
        'soft-cyan': 'var(--soft-cyan)',
        'hot-pink': 'var(--hot-pink)',
        'deep-pink': 'var(--deep-pink)',
        'soft-pink': 'var(--soft-pink)',
        electric: 'var(--electric)',
        void: 'var(--void)',
        abyss: 'var(--abyss)',
        shadow: 'var(--shadow)',
        slate: 'var(--slate)',
        muted: 'var(--muted)',
        dim: 'var(--dim)',
        ghost: 'var(--ghost)',
        // Semantic
        accent: 'var(--accent)',
        fg: 'var(--fg)',
        'fg-muted': 'var(--fg-muted)',
        'fg-subtle': 'var(--fg-subtle)',
        bg: 'var(--bg)',
        'bg-surface': 'var(--bg-surface)',
        'bg-elevated': 'var(--bg-elevated)',
        'bg-overlay': 'var(--bg-overlay)',
        info: 'var(--color-info)',
        danger: 'var(--color-danger)',
        warning: 'var(--color-warning)',
        // Transparent state surfaces
        'accent-ghost': 'var(--bg-accent-ghost)',
        'accent-dim': 'var(--bg-accent-dim)',
        'accent-soft': 'var(--bg-accent-soft)',
        'danger-ghost': 'var(--bg-danger-ghost)',
        'info-ghost': 'var(--bg-info-ghost)',
        'modal-overlay': 'var(--bg-modal-overlay)',
        // Semantic backgrounds
        'accent-bg': 'var(--color-accent-bg)',
        'info-bg': 'var(--color-info-bg)',
        'danger-bg': 'var(--color-danger-bg)',
      },
      fontFamily: {
        mono: ['var(--font-mono)'],
        display: ['var(--font-display)'],
      },
      fontSize: {
        xs: 'var(--text-xs)',
        sm: 'var(--text-sm)',
        base: 'var(--text-base)',
        md: 'var(--text-md)',
        lg: 'var(--text-lg)',
        xl: 'var(--text-xl)',
        '2xl': 'var(--text-2xl)',
      },
      fontWeight: {
        regular: 'var(--weight-regular)',
        medium: 'var(--weight-medium)',
        semibold: 'var(--weight-semibold)',
        bold: 'var(--weight-bold)',
      },
      letterSpacing: {
        tight: 'var(--tracking-tight)',
        normal: 'var(--tracking-normal)',
        wide: 'var(--tracking-wide)',
        wider: 'var(--tracking-wider)',
        widest: 'var(--tracking-widest)',
      },
      lineHeight: {
        tight: 'var(--leading-tight)',
        normal: 'var(--leading-normal)',
        loose: 'var(--leading-loose)',
      },
      spacing: {
        '2xs': 'var(--gap-2xs)',
        xs: 'var(--gap-xs)',
        sm: 'var(--gap-sm)',
        md: 'var(--gap-md)',
        lg: 'var(--gap-lg)',
        xl: 'var(--gap-xl)',
        '2xl': 'var(--gap-2xl)',
        '3xl': 'var(--gap-3xl)',
        // Section macro spacing
        'sp-xs': 'var(--sp-xs)',
        'sp-sm': 'var(--sp-sm)',
        'sp-md': 'var(--sp-md)',
        'sp-lg': 'var(--sp-lg)',
        'sp-xl': 'var(--sp-xl)',
        'sp-2xl': 'var(--sp-2xl)',
      },
      borderRadius: {
        none: 'var(--radius-none)',
        xs: 'var(--radius-xs)',
        sm: 'var(--radius-sm)',
        md: 'var(--radius-md)',
        pill: 'var(--radius-pill)',
      },
      borderColor: {
        subtle: 'var(--border-color-subtle)',
        base: 'var(--border-color-base)',
        strong: 'var(--border-color-strong)',
      },
      transitionTimingFunction: {
        flick: 'var(--ease-flick)',
        smooth: 'var(--ease-smooth)',
        sharp: 'var(--ease-sharp)',
        snap: 'var(--ease-snap)',
      },
      transitionDuration: {
        instant: 'var(--duration-instant)',
        fast: 'var(--duration-fast)',
        base: 'var(--duration-base)',
        slow: 'var(--duration-slow)',
        slower: 'var(--duration-slower)',
      },
    },
  },
  plugins: [],
}
