// GENERATED by scripts/vendor-dataset.mjs — do not edit by hand.
// Regenerate with `npm run vendor:dataset`. The dated snapshot is a versioned artifact (ADR 0022).
import type { Dataset } from '../atlas/types'
import dataset from './dataset-2026-09.json'

export const SNAPSHOT: Dataset = dataset as Dataset
